### ISSUE TITLE
Server auto launch at reboot, and as a daemon that restarts on failure

### ISSUE THREAD

**Issue by mitra42** [ArchiveLabs/dweb_gateway#1]
We need the usual scripting that can start the server automatically at reboot or after a crash. 

I know this is highly dependent on which version of Linux, so could use some sysadmin help here.

**Comment by keomabrun** [comment]
We can use supervisor ? http://supervisord.org/

**Comment by keomabrun** [comment]
I just came across this: https://immortal.run/
It looks young but promising.

**Comment by mitra42** [comment]
Thanks - looks like people here are familiar with supervisord so I'll use that.

**Comment by mitra42** [comment]
Working with ...
[program:dweb-gateway]
command=/usr/bin/python3 -m python.ServerGateway
directory = /usr/local/dweb_gateway
user = mitra
stdout_logfile = /var/log/dweb/dweb-gateway
stdout_logfile_maxbytes=500MB
#redirect_stderr = True
autorestart = True
environment=USER=mitra,PYTHONUNBUFFERED=TRUE
exitcodes=0
