### ISSUE TITLE
Single connection to DB & Redis

### ISSUE THREAD

**Issue by mitra42** [ArchiveLabs/dweb_gateway#12]
When the server starts it should connect ot Redis (read/write) and sqlite (read only)

**Comment by mitra42** [comment]
Sqlite connection didn't work - since there aren't thread-variables, and sqlite connections cant be used across threads.

Redis connection works. However , I can't figure out where the configuration (if any) is.   I understood there was a way to make Redis save material between runs, but can't see where this is done (or should be done). 

 Keoma - any ideas, I think it was you who set it up?

**Comment by keomabrun** [comment]
@mitra42 I haven't set up Redis to have persistent storage. I am not very comfortable with it. I will read about it and get back to you.

**Comment by mitra42** [comment]
Thanks. I'm offline mostly till sun eve

**Comment by mitra42** [comment]
Did you get a chance to look at this Keoma ?

**Comment by keomabrun** [comment]
@mitra42 no yet.

**Comment by mitra42** [comment]
This might be the cause (partially) of Issue #14

**Comment by mitra42** [comment]
Ok - I reviewed the config file and it looks like its persisting automatically.
