### ISSUE TITLE
Incorporate tests in CI tests in test/

### ISSUE THREAD

**Issue by mitra42** [ArchiveLabs/dweb_gateway#14]
@keomabrun setup Travis, but it needs some more tests in test/ building off the tests in sripts/test.sh

**Comment by keomabrun** [comment]
I get a 502 error when trying to reach the links from `scripts/test.sh`: https://gateway.dweb.me/info

**Comment by mitra42** [comment]
Thanks for spotting this, I'll take a look.

**Comment by mitra42** [comment]
Hmmm - server is still running on that port, but generating empty replies. which makes it hard to figure out what is causing it to fail, i.e. where it is stuck. 

I'm probably going to have to figure out Issue https://github.com/ArchiveLabs/dweb_gateway/issues/2 re getting logger setup so I can see what is causing this. Have you setup logger before?

**Comment by keomabrun** [comment]
yes, I am on it. I think I will setup a simple logger for now. I'll try to push something later today.

**Comment by mitra42** [comment]
logger is there now (thanks Keoma).

I'm seeing the 502 Keoma references from tests ... which goes to 
https://gateway.dweb.me/content/contenthash/5dr1gqVNt1mPzCL2tMRSMnJpWsJ5Qs?verbose=True

Three sub-issues:
a) I'm concerned it doesn't show up in the log. see #2 
b) And then why it didn't give a useful error message (like "not found")
c) I think it fails because REDIS isn't persistent - so it didn't retain the info on that hash see #12

**Comment by mitra42** [comment]
a) was the problem Keoma identified with arguments to logging (documented to work, but dont appear to)
b) was related to a - error not getting all the way out
c) fails because of #12 (Redis persistance) BUT, should be handled better in terms of falling back to searching for it.

**Comment by mitra42** [comment]
I've made it search for DOI's but that hash looks truly a wrong one ! So now happy with a bad error.
