### ISSUE TITLE
Do we need a dot before local import ?

### ISSUE THREAD

**Issue by keomabrun** [ArchiveLabs/dweb_gateway#15]
When I run the ServerGateway using `python ServerGateway.py`, I get the following error:
```
Traceback (most recent call last):
  File "ServerGateway.py", line 4, in <module>
    from .miscutils import mergeoptions
ValueError: Attempted relative import in non-package
```
I am tempted to remove the dot in `from .miscutils import mergeoptions`.

### Python Ref
https://docs.python.org/3/tutorial/modules.html#intra-package-references

**Comment by mitra42** [comment]
Please dont change it ! It took me forever to find something that worked in both Python2 and Python 3, and in PyCharm and when running unit tests. 

The trick that caught you is you need to run it from one level up, i.e. 
cd .../dweb_gateway  ; python3 -m python.ServerGateway
you can see this in scripts/run_dweb_me.sh

**Comment by keomabrun** [comment]
I see ! Alright :)
